# Generated by Django 6.0.7 on 2026-08-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
            preserve_default=False,
        ),
    ]
