# Generated by Django 6.0.7 on 2026-08-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
