# Generated by Django 6.0.7 on 2026-08-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matriculado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
    ]
